services:

  web:
    build: .
    command: sh -c "python manage.py makemigrations films; 
                    python manage.py migrate films; 
                    python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    shm_size: 128mb
    restart: always
    container_name: postgres
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb

    env_file: .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}

    ports:
      - "5432:5432"
